### PR TITLE
Add script section to index.html

### PR DESCRIPTION
**Pull request by bjhammaker**

### CODE REVIEW

**Comment by bjhammaker** [comment]
I added an input section, and a button to add the input to the end of the list. I'd welcome any feedback on the script!

**Review by davidhammaker — APPROVED** [review]
I would typically request that commented code be removed before merging, but you may want to keep it there for learning / further development.

**Comment by bjhammaker** [comment]
I want to follow any and all best practices along the way, so I went ahead and removed the commented code. Honestly I had forgot about that line.

**Review by davidhammaker — APPROVED** [review]
Looks good!
It works great, so I'm approving!
The use of `var` to define variables and functions isn't my favorite, but I honestly probably started with that, too. We'll update this in the future if necessary, but it works as-is. Good job!

**Pull request merged**
